[package]
name = "bxt-macros"
version = "0.1.0"
authors = ["Ivan Molodetskikh <yalterz@gmail.com>"]
edition = "2021"
license = "GPL-3.0-or-later"

[lib]
proc_macro = true

[dev-dependencies]
trybuild = "1.0.64"
